Add: [CDN] code and config to generate required files for CDN (#4)
This is including the workflow scripts to automate the CDN
generator.

The CDN generator includes:
 - index.html: an index file (as S3 / CloudFront / CloudFlare
               cannot do this for us)
 - folders.yaml: to be able to script walking the CDN
 - latest.yaml: a short summary for the latest release of a
                category
 - manifest.yaml: manifest file per release

This can be generated for everything, or only for a single (new)
release. The first is a rebuild, the second is for when a new
release is pushed to the CDN. In the second case the bare minimum
will be done to come to the same result as a full rebuild would
have done.

This requires read access to the S3 via the AWS API.

diff --git a/.github/workflows/new_openttd_release.yml b/.github/workflows/new_openttd_release.yml
--- a/.github/workflows/new_openttd_release.yml
+++ b/.github/workflows/new_openttd_release.yml
@@ -7,31 +7,42 @@ on:
     - new_master
     - new_pullrequest
 
+# client_payload should contain:
+#  - version: the version of the new release, e.g.: 20200101-master-g12345
+#  - folder: the folder in which the release is located openttd-nightlies/2020
+
 jobs:
   new_release:
     name: New OpenTTD release
     runs-on: ubuntu-latest
 
     steps:
-    - name: Trigger website (staging)
-      uses: peter-evans/repository-dispatch@v1
-      with:
-        token: ${{ secrets.DEPLOYMENT_TOKEN }}
-        repository: OpenTTD/website
-        event-type: publish_master
+    - name: Sanity check
+      run: |
+        set -x
 
-    - name: Trigger website (Production)
+        if [ -z "${{ github.event.client_payload.version }}" ]; then
+          echo "::error::version in client_payload is not set"
+          exit 1
+        fi
+        if [ -z "${{ github.event.client_payload.folder }}" ]; then
+          echo "::error::folder in client_payload is not set"
+          exit 1
+        fi
+
+    - name: Trigger 'update CDN'
       uses: peter-evans/repository-dispatch@v1
       with:
         token: ${{ secrets.DEPLOYMENT_TOKEN }}
-        repository: OpenTTD/website
-        event-type: publish_latest_tag
+        repository: OpenTTD/workflows
+        event-type: update_cdn
+        client-payload: '{"version": "${{ github.event.client_payload.version }}", "folder": "${{ github.event.client_payload.folder }}"}'
 
     - if: github.event.action == 'new_master'
-      name: Trigger docs
+      name: Trigger 'publish docs'
       uses: peter-evans/repository-dispatch@v1
       with:
         token: ${{ secrets.DEPLOYMENT_TOKEN }}
         repository: OpenTTD/workflows
         event-type: publish_docs
-        client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
+        client-payload: '{"version": "${{ github.event.client_payload.version }}", "folder": "${{ github.event.client_payload.folder }}"}'
diff --git a/.github/workflows/publish_docs.yml b/.github/workflows/publish_docs.yml
--- a/.github/workflows/publish_docs.yml
+++ b/.github/workflows/publish_docs.yml
@@ -5,12 +5,37 @@ on:
     types:
     - publish_docs
 
+# client_payload should contain:
+#  - version: the version of the new release, e.g.: 20200101-master-g12345
+#  - folder: the folder in which the release is located openttd-nightlies/2020
+
 jobs:
   publish_docs:
     name: Publish docs
     runs-on: ubuntu-latest
 
     steps:
+    - name: Sanity check
+      run: |
+        set -x
+
+        if [ -z "${{ github.event.client_payload.version }}" ]; then
+          echo "::error::version in client_payload is not set"
+          exit 1
+        fi
+        if [ -z "${{ github.event.client_payload.folder }}" ]; then
+          echo "::error::folder in client_payload is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.DOCS_S3_BUCKET }}" ]; then
+          echo "::error::secret DOCS_S3_BUCKET is not set"
+          exit 1
+        fi
+        if [ -z "${{ secrets.DOCS_CF_DISTRIBUTION_ID }}" ]; then
+          echo "::error::secret DOCS_CF_DISTRIBUTION_ID is not set"
+          exit 1
+        fi
+
     - name: Checkout
       uses: actions/checkout@v2
 
@@ -19,45 +44,33 @@ jobs:
         set -x
 
         VERSION=${{ github.event.client_payload.version }}
-
-        if [ -z "${VERSION}" ]; then
-          echo "::error::version in client_payload is not set"
-          exit 1
-        fi
-        if [ -z "${{ secrets.S3_BUCKET }}" ]; then
-          echo "::error::secret S3_BUCKET is not set"
-          exit 1
-        fi
-        if [ -z "${{ secrets.CF_DISTRIBUTION_ID }}" ]; then
-          echo "::error::secret CF_DISTRIBUTION_ID is not set"
-          exit 1
-        fi
+        FOLDER=${{ github.event.client_payload.folder }}
 
         # Fetch and extract the docs
-        curl --fail -s -L -o docs-ai.tar.xz https://proxy.binaries.openttd.org/openttd-nightlies/${VERSION}/openttd-${VERSION}-docs-ai.tar.xz
-        curl --fail -s -L -o docs-gs.tar.xz https://proxy.binaries.openttd.org/openttd-nightlies/${VERSION}/openttd-${VERSION}-docs-gs.tar.xz
-        curl --fail -s -L -o docs.tar.xz https://proxy.binaries.openttd.org/openttd-nightlies/${VERSION}/openttd-${VERSION}-docs.tar.xz
+        curl --fail -s -L -o docs-ai.tar.xz https://cdn.openttd.org/${FOLDER}/${VERSION}/openttd-${VERSION}-docs-ai.tar.xz
+        curl --fail -s -L -o docs-gs.tar.xz https://cdn.openttd.org/${FOLDER}/${VERSION}/openttd-${VERSION}-docs-gs.tar.xz
+        curl --fail -s -L -o docs.tar.xz https://cdn.openttd.org/${FOLDER}/${VERSION}/openttd-${VERSION}-docs.tar.xz
         tar xf docs-ai.tar.xz
         tar xf docs-gs.tar.xz
         tar xf docs.tar.xz
 
         # Sync all the new/modified files
-        aws s3 sync --only-show-errors docs/root/ s3://${{ secrets.S3_BUCKET }}/
-        aws s3 sync --only-show-errors docs/errors/ s3://${{ secrets.S3_BUCKET }}/errors/
-        aws s3 sync --only-show-errors openttd-${VERSION}-docs-ai/html/ s3://${{ secrets.S3_BUCKET }}/ai-api/
-        aws s3 sync --only-show-errors openttd-${VERSION}-docs-gs/html/ s3://${{ secrets.S3_BUCKET }}/gs-api/
-        aws s3 sync --only-show-errors openttd-${VERSION}-docs/html/ s3://${{ secrets.S3_BUCKET }}/source/
+        aws s3 sync --only-show-errors docs/root/ s3://${{ secrets.DOCS_S3_BUCKET }}/
+        aws s3 sync --only-show-errors docs/errors/ s3://${{ secrets.DOCS_S3_BUCKET }}/errors/
+        aws s3 sync --only-show-errors openttd-${VERSION}-docs-ai/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/ai-api/
+        aws s3 sync --only-show-errors openttd-${VERSION}-docs-gs/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/gs-api/
+        aws s3 sync --only-show-errors openttd-${VERSION}-docs/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/source/
 
         # Delete any unknown file; this is a separate step, as 'aws s3 sync'
         # can delete before uploading, which could mean files temporary link
         # to invalid files.
-        aws s3 sync --only-show-errors --delete docs/errors/ s3://${{ secrets.S3_BUCKET }}/errors/
-        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs-ai/html/ s3://${{ secrets.S3_BUCKET }}/ai-api/
-        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs-gs/html/ s3://${{ secrets.S3_BUCKET }}/gs-api/
-        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs/html/ s3://${{ secrets.S3_BUCKET }}/source/
+        aws s3 sync --only-show-errors --delete docs/errors/ s3://${{ secrets.DOCS_S3_BUCKET }}/errors/
+        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs-ai/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/ai-api/
+        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs-gs/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/gs-api/
+        aws s3 sync --only-show-errors --delete openttd-${VERSION}-docs/html/ s3://${{ secrets.DOCS_S3_BUCKET }}/source/
 
         # Invalidate the cache of the CloudFront distribution
-        aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"
+        aws cloudfront create-invalidation --distribution-id ${{ secrets.DOCS_CF_DISTRIBUTION_ID }} --paths "/*"
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
